name: #
longname: Survival
default-channel: s
default-listen: [S, Server, Global]
chat-server: '127.0.0.1'
console-listen-other-servers: true
console-hide-chat: false
hide-playerlist-onJoin: false
server-filter-string: ''
strings:
  player-welcome: '&aWelcome &e%player% &ato the server!'
  player-join: '%prefix%%player% &ehas joined %server%!'
  player-quit: '%prefix%%player% &ehas left %server%!'
  message: '&f<&3%server%&7%channel%&f>%prefix% %player%: &7%message%'
  action: '&f<&3%server%&7%channel%&f> * %prefix%%player% &f%message%'
  pm_send: '&7(to %to%) %message%' # you can also use %from%
  pm_receive: '&7(from %from%) %message%' # you can also use %to%